### PR TITLE
Made the examples self contained

### LINKED ISSUE #4: The examples aren't self-contained
I tried copying over the code from the [antd Form List](https://opensource.ebay.com/nice-form-react/antd/#form-list), added the necessary dependencies and ran into this issue:
```
config.tsx:62 Uncaught Error: Widget 'form-list' not defined. Did you define it?
    at Object.getWidgetDef (config.tsx:62:15)
    at NiceForm.tsx:65:26
    at Array.map (<anonymous>)
    at NiceForm (NiceForm.tsx:24:25)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
```
By copying this over from `packages/examples-antd/src/main.tsx` into the example code, it does work:

```tsx
import { config as niceFormConfig } from '@ebay/nice-form-react';
import antdAdapter from '@ebay/nice-form-react/adapters/antdAdapter';

niceFormConfig.addAdapter(antdAdapter);
```

Because `antdAdapter` defines the `form-list` widget.
This is most likely the same for the formik form-list, but might happen in even more files.

To make it easier for developers to play around with `nice-form-react`, it'd be better if the example code is self-contained.

### PR DESCRIPTION
**Pull request by leroydev**
Closes #4.
Also makes all the examples lazy loaded. This should speed up first load speed of the examples website but should be tested whether this works properly in a production build too. Locally for me with a production build served with [http-server](https://www.npmjs.com/package/http-server) it did work.

### CODE REVIEW

**Comment by supnate** [comment]
Hi @leroydev , thank you very much for deep dive into code and propose optimization!

However, adapter is designed to be a global config. Just like you need to config global providers for redux, some UI libs, etc. So using nice form consists of two parts, one for config and the other is real usage.

**Comment by leroydev** [comment]
Hi @supnate, thanks for taking the time to review quickly!
What do you think about adding a comment above the example code that adds the adapters, that mentions this should only be done globally but is done within the example to make them self-contained?
Then you have the best of both worlds, users can more quickly setup an example locally to play around with it and it is clear to them that the adapters is supposed to be global configuration.

If not, I do feel that including the definition of the custom datepicker in each example does add value.
Otherwise the user will be searching for a bit and would have to run into the one example that does have that code in it.

And the lazy loading should make the docs faster to load so might also be an improvement you want to consider.

Let me know which parts you want in what form and I'll make adjustments 🙂

**Comment by supnate** [comment]
Thanks @leroydev . 

1. The get started section in readme should help users to know how to configure nice form. Examples mainly shows different scenarios of usage.
2. For widget definition, we think it's usually configured globally for common widgets to avoid duplicated code. But I agree adding a doc link would be helpful.
3. Lazy load for examples code is good change 👍

**Comment by leroydev** [comment]
Closed in favor of #6

**Pull request closed without merging**
